version: '3.9'

services:

  effects:
    container_name: effects
    build:
      context: ./services/effects
      dockerfile: Dockerfile-dev
    volumes:
      - './services/effects:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig

  nginx:
    container_name: nginx
    build: ./services/nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - effects
    links:
      - effects