FROM python:3.9

# install environment dependencies
RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    netcat \
  && apt-get -q clean

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
COPY ./requirements.txt /usr/src/app/requirements.txt

# install requirements
RUN pip install -r requirements.txt

# add entrypoint.sh
COPY ./entrypoint-prod.sh /usr/src/app/entrypoint-prod.sh

# add app
COPY . /usr/src/app

# change the permission of the bash file
RUN chmod +x entrypoint-prod.sh

# run server
ENTRYPOINT ["bash", "./entrypoint-prod.sh"]
